name: Deploy Mechanic Checker Netcore
on:
  push:
    branches:
    - develop
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
  
    - name: Create appsettings.json string
      run: |
        APPSETTINGS_JSON_STR=$(cat << EOF
        { 
          "ConnectionStrings": {
            "DefaultConnectionString": ${{ secrets.NETCORE_APPSETTINGS_DEFAULTCONNECTIONSTRING }}
          }
        }
        EOF
        )
        echo "APPSETTINGS_JSON_STR<<EOF" >> $GITHUB_ENV
        echo "$APPSETTINGS_JSON_STR" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Create appsettings.json file for Production
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "appsettings.json"
        FILE_DATA: ${{ env.APPSETTINGS_JSON_STR }}

    - name: Generate .NET deployment package
      run: | 
        mv appsettings.json MechanicChecker/MechanicChecker
        cd MechanicChecker/MechanicChecker
        dotnet publish -c Release -o site
        cd site
        zip -r ../deploy_bundle.zip *

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: mechanic-checker-netcore
        environment_name: Mechaniccheckernetcore-env
        version_label: "${{ github.run_id }}-${{ github.run_number }}-${{ github.actor }}"
        region: us-east-1
        deployment_package: MechanicChecker/MechanicChecker/deploy_bundle.zip
